apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.name }}
    release: {{ .Values.release }}
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000