kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dutchellie/proper-website-2
    target: api
    tags: latest