kind: pipeline
type: kubernetes
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dutchellie/proper-website-2
    tags: latest

---

kind: pipeline
type: kubernetes
name: deploy-staging

- name: deploy-staging
  image: pelotech/drone-helm3
  settings:
    mode: upgrade
    chart: .drone/helm/chart
    namespace: default
    release: newsite-staging
    values_files:
      - .drone/helm/values.yaml
    values:
      - ingress.tls.host: newsite.staging.dutchellie.nl
      - ingress.hosts[0].host: newsite.staging.dutchellie.nl
    kube_api_server:
      from_secret: staging_api_server
    kube_token:
      from_secret: staging_kube_token
    kube_certificate:
      from_secret: staging_kube_certificate
    kube_service_account: drone-deploy
    dry_run: true