name: newsite-deployment
annotations: {}
release: latest
replicas: 1
podAnnotations: {}
containerName: newsite
image: dutchellie/proper-website-2:latest
imagePullPolicy: Always
containerEnv: []

service:
  name: newsite-service
  annotations: {}

ingress:
  name: newsite-ingress
  annotations: {}
  className: nginx
  tls: []
  # tls:
  # - hosts:
  #   - example.com
  #   secretName: example-tls
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix