name: newsite-prod
service:
  name: newsite-prod
ingress:
  name: newsite-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: "newsite.dutchellie.nl"
    nginx.ingress.kubernetes.io/configuration-snippet: |   
      add_header Content-Security-Policy "frame-ancestors 'self' https://forestofunix.xyz";
      proxy_hide_header X-Frame-Options ;
  tls:
    - hosts:
        - newsite.dutchellie.nl
      secretName: newsite-tls
  hosts:
    - host: newsite.dutchellie.nl
      paths:
        - path: /
          pathType: Prefix