name: newsite-staging
containerEnv:
  - name: APIURL
    value: https://api.quenten.nl/api/testing
service:
  name: newsite-staging
ingress:
  name: newsite-staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    external-dns.alpha.kubernetes.io/hostname: "staging.quenten.nl"
    nginx.ingress.kubernetes.io/configuration-snippet: |   
      add_header Content-Security-Policy "frame-ancestors 'self' https://forestofunix.xyz";
      proxy_hide_header X-Frame-Options ;
  tls:
    - hosts:
        - staging.quenten.nl
      secretName: newsite-staging-tls
  hosts:
    - host: staging.quenten.nl
      paths:
        - path: /
          pathType: Prefix