name: newsite-staging
service:
  name: newsite-staging
ingress:
  name: newsite-staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    external-dns.alpha.kubernetes.io/hostname: "newsite.staging.dutchellie.nl"
  tls:
    - hosts:
        - newsite.staging.dutchellie.nl
      secretName: newsite-staging-tls
  hosts:
    - host: newsite.staging.dutchellie.nl
      paths:
        - path: /
          pathType: Prefix