baseURL: staging.quenten.nl
name: newsite-staging
containerEnv:
  - name: APIURL
    value: https://api.quenten.nl/api/testing
service:
  name: "{{ .Values.name }}"
ingress:
  name: "{{ .Values.name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.baseURL }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |   
      add_header Content-Security-Policy "frame-ancestors 'self' https://forestofunix.xyz";
      proxy_hide_header X-Frame-Options ;
  tls:
    - hosts:
        - "{{ .Values.baseURL }}"
      secretName: "{{ .Values.name }}-tls"
  hosts:
    - host: "{{ .Values.baseURL }}"
      paths:
        - path: /
          pathType: Prefix